version: '3'

services:
  chronicle-emulator:
    image: ghcr.io/chocpanda/chronicle-emulator:main
    # image: plork/chronicle-emulator
    ports:
    - 3000:3000
    volumes:
    - ./public.pem:/public.pem:ro
    command:
    - -p
    - /public.pem
